### ISSUE TITLE
server文件夹下面有一些mac下的binary

### ISSUE THREAD

**Issue by a1exwang** [JianxinMa/v9.js#14]
- 希望能提供这些binary file的源码和makefile, 否则在我这里(ubuntu 16.04 x64)无法运行

**Comment by JianxinMa** [comment]
cemulator就是v9原来的C版本模拟器。
其他的二进制文件来自于：
gcc-5 -o xvcc -O3 -m32 xvcc.c
gcc-5 -o mkfs -O3 -m32 mkfs.c
（见init.sh）

**Comment by JianxinMa** [comment]
cemulator只是我自己用来测试模拟器实现的，你们应该不需要。

**Comment by JianxinMa** [comment]
gcc版本需要是gcc-multilib才能跨平台编译32bit的程序（那个-m32选项）。
你可能需要:
sudo apt-get uninstall gcc
sudo apt-get install gcc-multilib

**Comment by a1exwang** [comment]
ok! 明白了
