### ISSUE TITLE
!x cannot judge whether a number is zero in javascript

### ISSUE THREAD

**Issue by paulzfm** [JianxinMa/v9.js#15]
``` javascript
function execDIV() {
        if (!regB) {
            regTrap = FARITH;
            regNextHdlr = hdlrExcpt;
            return;
        }
        regA = (regA / regB) >>> 0;
        regNextHdlr = hdlrChkpc;
        return;
}

```

`!regB = true` if and only if `regB == null or regB == undefined`!

Thus, you need `regB == 0` to check whether regB is zero.

**Comment by JianxinMa** [comment]
Oops, I ran `!0` in node, and it gave me a `true`. That's why I wrote it that way...

Will correct it in my next commit.

**Comment by JianxinMa** [comment]
I am now confused. !regB seems fine to me. According to https://msdn.microsoft.com/en-us/library/zz722703(v=vs.94).aspx, "for the ! operator, if expression is nonzero, result is zero. If expression is zero, result is 1".

**Comment by paulzfm** [comment]
You are right. `1 == true` is `true` but `1 === true` is `false`.
