### ISSUE TITLE
请问调试信息中的栈偏移量的具体定义

### ISSUE THREAD

**Issue by a1exwang** [JianxinMa/v9.js#18]
l n stk +24 (uint)
l s stk +16 (ptr(void))
l d stk +8 (ptr(void))

比如这段调试信息, +24, +16, +8这是指进入函数时该变量地址相对sp的偏移量吗?

**Comment by JianxinMa** [comment]
stk表示偏移值是相对"栈帧的起始地址"。
调试信息应该有打出相应的代码，你可能需要仔细体会下才能弄准确。

**Comment by JianxinMa** [comment]
建议写个小程序，编译一下看看结果。

编译器在`src/xvcc.c`，用`gcc -m32 -o xvcc xvcc.c``获得编译器。
编译选项示例，``./xvcc -s -Iroot/lib -o root/usr/scratch root/usr/scratch.c``，其中-s表示打出代码注释（注意编译选项的位置最好不要换，可能会出问题）。之后你会看到``root/usr/scratch.d``，就是调试信息。

**Comment by a1exwang** [comment]
栈帧的定义是指令集相关的吧, 我们的指令集访问局部变量是用$fp+offset. 不知道v9是如何定义的

**Comment by JianxinMa** [comment]
v9只是没有显示的fp寄存器而已，栈帧还是有的，编译器根据相对栈帧的offset计算出局部变量相对sp的offset，然后用sp+相对sp的offset访问之。

我这里要的是相对栈帧的offset，不是相对sp的offset（因为sp会变）。

但我不确定v9里的栈帧起始地址和你们的$fp是否对应（比如，返回地址究竟算是子栈帧的，还是父栈帧，这个不知道会不会有错别），建议用v9编译器试验下。
