### ISSUE TITLE
请问机器码对应行号可不可以不全

### ISSUE THREAD

**Issue by a1exwang** [JianxinMa/v9.js#19]
比如这个, 行号有重复的
i 0x0000687c root/etc/os.c 2621
i 0x00006880 root/etc/os.c 2621
i 0x00006884 root/etc/os.c 2621
i 0x00006888 root/etc/os.c 2621
i 0x0000688c root/etc/os.c 2621
i 0x00006890 root/etc/os.c 2622
可不可以这样
i 0x0000687c root/etc/os.c 2621
i 0x00006890 root/etc/os.c 2622

**Comment by JianxinMa** [comment]
每一条指令都需要对应行号，所以采用前一种，不要删除。

**Comment by a1exwang** [comment]
elf的调试信息只产生了每行c代码对应的机器码地址, 并没有给出每条机器码对应的行号... 所以只能估计了, 不能保证行号一定是正确的..
