### ISSUE TITLE
请问调试信息中结构体的一些问题

### ISSUE THREAD

**Issue by a1exwang** [JianxinMa/v9.js#20]
```
# 接下来给出定义的结构体的信息：
d struct pollfd (8|(fd:+0:(int))(events:+4:(short))(revents:+6:(short)))
# ...省略很多很多...
```

请问结构体嵌套如何表示? 要全部展开吗?

**Comment by JianxinMa** [comment]
有名字的结构体不展开。详情：这是用伪代码里的print_struct_type_str生成的，而它在处理成员时会调用print_type_str。print_type_str展不展开取决于struct是否是匿名结构体。

**Comment by JianxinMa** [comment]
如果你是担心下面这种情况的话：
struct st {
  struct st *m;
}
我只能说我之前没有考虑过这种情况，就暂时忽视它吧。
更新：不过好像这种情况下，我的那份伪代码并不会出现问题。
