### ISSUE TITLE
生成可执行文件和elf的程序在这个仓库

### ISSUE THREAD

**Issue by a1exwang** [JianxinMa/v9.js#21]
https://github.com/a1exwang/alex2v9
请参考readme

**Comment by a1exwang** [comment]
应该差不多了, 不知道怎么测试

**Comment by JianxinMa** [comment]
How to compile your compiler? Simply clone your LLVM repo and `make`?
(Unable to type Chinese right now...)

**Comment by a1exwang** [comment]
mac下的clang生成的llvm ir有问题, 之前没搞定, 我这边有个ubuntu服务器, 你告诉我用户名和公钥, 我帮你创建一个用户, 上面有编译好的

**Comment by JianxinMa** [comment]
Don't worry, I am using Debian these days (and that's why I have no pinyin input method). If you can provide a shell script to compile your LLVM, that would be great.

**Comment by a1exwang** [comment]
我有一个自动clone所有项目编译llvm并测试的脚本, 但是注意, 要放在一个新建的文件夹里, 否则容易吧当前文件夹搞乱, 使用方法: 

```
  mkdir alex && cd alex
  git clone https://github.com/a1exwang/alex-cpu-test.git -b master alex-machine-tests
  cd alex-machine-tests && ./setup
```

运行之前可以打开看一下脚本, 里面安装了所有依赖包(git, clang,ruby,node等等), 装过的你可以删掉这部分脚本

**Comment by JianxinMa** [comment]
Hi,

Can you briefly describe how to compile source code using your compiler?
Are the compiler in llvm-build/bin? How to use it?

**Comment by a1exwang** [comment]
抱歉, 之前没看到这里..
是这样的, alex-cpu-test中有一个build文件, 用./build -l llvm_bin_path -i inc_path -s source_path会递归编译所有source_path下的.c文件, 生成a.out是elf文件, 再用./alex2v9 a.out a.v9转换成v9格式, ./dwarf2v9 a.out xxx生成调试符号. 其中llvm_bin_path应该是llvm-build/bin的相对路径或者绝对路径
