### ISSUE TITLE
请问以下情况应该如何处理

### ISSUE THREAD

**Issue by a1exwang** [JianxinMa/v9.js#22]
```
struct {
  struct b {
    int x;
  };
} s;
```

匿名结构体包含匿名成员,
print_struct_type_str中用了member_name(m), 不知道member_name里面怎么实现的.

**Comment by JianxinMa** [comment]
...
我之前没想到这种情况，我只考虑了下面这种：
struct {
  struct b {
    int x;
  } i_am_member;
} s;
那这种自然就有member_name（这里就是i_am_member）了....

至于你说的那种情况，那种情况应该是GCC扩展，标准C好像并没有说可以那样：
http://stackoverflow.com/a/14248127

顺带一提：我之前的文档提到的anonymous struct应该是指unnamed struct（指结构体没名字，不是成员没名字），我之前没注意，写混了。
